<?php
/**
 * @var $this Wsu_Launcher_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('#') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="#" target="_blank" style="float:right;">
            <img src="#" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('wsu_launcher')->__('Wsu Launcher is an intuitive and powerful keystroke launcher for Magento Admin Panel.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_launcher')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_launcher')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_launcher')->__('here'); ?></a>.</p>NOTE: UPDATE
    </div>
</div>