<?php
/**
 * @var $this Wsu_Launcher_Block_Adminhtml_Launcher
 */
?>

    <script type="text/javascript">
        Event.observe(window, 'load', function() {
            $('nav').insert('<li id="wsulauncher-status"><a id="wsulauncher-icon" href="#" target="_blank" title="WsuCode"><span>&nbsp;</span></li>');
           /* var launcher = new WsuLauncher({
                dataLocation: '<?php echo $this->helper('adminhtml')->getUrl('adminhtml/wsu_dropshipper/index') ?>',
                onReady: function() {
                    $('wsulauncher-status').addClassName('on');
                },
                onError: function(error) {
                    $('wsulauncher-icon').title = error.replace(/"/g, '&quot;');
                },
                minChars: <?php echo $this->getMinChars(); ?>,
                maxResults: <?php echo $this->getMaxResults(); ?>,
                resetOnHide: <?php echo $this->getResetOnHide(); ?>,
                useScope: <?php echo $this->getUseScope(); ?>,
                showIcon: <?php echo $this->getShowIcon(); ?>,
                showScope: <?php echo $this->getShowScope(); ?>,
                showText: <?php echo $this->getShowText(); ?>
            });
            $('wsulauncher-icon').observe('click', launcher.show.bind(launcher));*/
			
			
			(function($){
				$('#wsulauncher-icon').on("click",function(){
					alert('the product list goes here');
					});
				})(jQuery);
			
			
			
        });
    </script>
<?php //if ($this->isEnabled()): ?><?php //endif; ?>