<?php $order = $this->getOrder(); ?>
<form id="drop_order_form" name="drop_order_form" action="<?php echo $this->getLocation() ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"  />
    <div align="right" style="margin-bottom:18px">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td class="a-right">
                   
                    <button type="button"  class="scalable save" type="button" onclick="sendMail('<?php echo $this->sendMailAction() ?>')"><span><?php echo $this->__('Save and Send Mail');?></span></button>
                    
                    <button type="submit"  class="scalable save" type="button"><span><?php echo $this->__('Save');?></span></button>
                    
                </td>
            </tr>
        </table>
    </div>
    <div class="grid">
        <table class="data" cellspacing="0" id="dropshipper-table">
            <col width="1" />
            <col />
            <col width="150" />
            <col width="150" />
            <thead>
                <tr class="headings">
                    <th></th>
                    <th class="a-left"><?php echo $this->__('Dropshipper Name');?></th>
                    <th class="a-left"><?php echo $this->__('Product Name');?></th>
                    <th class="a-left"><?php echo $this->__('Status');?></th>
                </tr>
            </thead>
            <?php $items = $this->getDropshippersOrderedItems(); ?>
            <?php $_dropshippers = Mage::getModel('wsu_dropshipper/dropshipper')->getCollection();?>
            <?php $i = 0; ?>
            <tbody>
            <?php if(count($items)):?>
                <?php foreach($items as $_item):?>
                    <?php if (!$_item->isDeleted()):?>
                        <?php $_origDropshipper = Mage::getModel('wsu_dropshipper/order')->getDropshipperByItem($_item->getId()); ?>
                         <tr>
                            <td><input type="checkbox" name="dropshipper[<?php echo $i; ?>][item_id]" value="<?php echo $_item->getId()?>" /></td>
                            <td class="a-left">
                                <?php if(count($_dropshippers)): ?>
                                    <select class='required-entry' name="dropshipper[<?php echo $i; ?>][id]" >
                                    <option value=""><?php echo $this->__('Dropshipper Not Assigned'); ?></option>
                                    <?php foreach ($_dropshippers as $_dropshipper): ?>
                                        <option <?php if($_origDropshipper && $_origDropshipper->getDshipperId() == $_dropshipper->getDshipperId()):?> selected="selected" <?php endif;?> value="<?php echo $_dropshipper->getDshipperId();?>"><?php echo $_dropshipper->getName();?></option>
                                    <?php endforeach;?>
                                    </select>
                              <?php endif;?>               
                            </td>  
                            <td class="a-left"><?php echo $_item->getName(); ?></td> 
                            <td class="a-left"> <?php echo  $_origDropshipper && $_origDropshipper->getMailStatus() ? $this->__("Mail sent") : $this->__("Mail Not sent");?></td>          
                        </tr> 
                    <?php $i++; endif;?>
                <?php  endforeach;?>
            <?php else:?>
                <tr>
                    <td colspan="3" class="a-center"><?php echo $this->__('No Records.');?></td>
                </tr>
            <?php endif;?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('dropshipper-table')</script>
    </div>
</form>

<script type="text/javascript" language="javascript">
    function sendMail(action)
    {
        $('drop_order_form').action = action;
        $('drop_order_form').submit();
    }
      <?php if($this->getRequest()->getParam('tab')=='sales_order_view_tabs_dropshipper') : ?>
    Event.observe(window, 'load', function() {
        setTimeout(function(){                                   
            someNode = $('sales_order_view_tabs_dropshipper');
            sales_order_view_tabsJsTabs.showTabContent(someNode);    
        },100);    
        });
    <?php endif; ?>
</script>
